### ISSUE TITLE
Readme :: Install and setup instructions

### ISSUE THREAD

**Issue by CiTroNaK** [terribly-lazy/slack-roll-command#1]
Hi,
thank you for this slack roll command.

Could you please extend readme about install and setup instructions?
Thank you very much.

Best regards,
Petr

**Comment by CiTroNaK** [comment]
Sorry, I found it at https://github.com/terribly-lazy/slack-command-server.

**Comment by terribleplan** [comment]
Thanks for asking, I will add a link to the runner from the README.
